### ISSUE TITLE
请问这个新增的自动领取每日和访问线索怎么使用啊？

### ISSUE THREAD

**Issue by q793200739** [zsppp/Arknights-Sora#1]
作战结束之后控制台显示无法识别当前界面，然后明日方舟的界面就停在使用体力药的那个界面

**Comment by zsppp** [comment]
刀客塔你好，
  正常情况下作战结束后会自动去领取每日和访问线索。
按照问题描述来推测，应该是代码判断不严谨、或者图片识别的坐标没调正确。

问一下使用的是什么模拟器？方便的话，在作战结束后停留的界面用模拟器截图，上传到issues

**Comment by q793200739** [comment]
我用的是雷电模拟器
![image](https://user-images.githubusercontent.com/67819437/120613699-0b0e9200-c489-11eb-990a-b3be2928cc8b.png)
如果体力没用完就会在这个界面

**Comment by zsppp** [comment]
做了些调整，拉取代码试试

**Comment by q793200739** [comment]
已解决，辛苦作者了
