### ISSUE TITLE
2021/7/2更新后加入一键领取每日任务功能

### ISSUE THREAD

**Issue by LoveYourEnemy** [zsppp/Arknights-Sora#2]
由于只会用打包后的exe(Gitee上的v1.02)版本, 小生没有能力检测v1.03加入的一键领取每日任务是否在2021/7/2更新后也可以自动一键领取
另外v1.02版本下
1. 程序打开后第一次总是检测不到夜神模拟器(64位模拟器 7.0.1.1 1280x720 2CPU 3072MB内存), 需要按change device 有时候要按2次才能出现adb地址

2. 有时候点开程序就会闪退1到2次, 然后才能进行1的操作

不知道之后的版本是否有被优化(哭诉希望zsppp能够把最新版本也打包一下)

**Comment by zsppp** [comment]
刀客塔你好，
    本人用的是雷电模拟器，没有尝试过在夜神模拟器使用脚本，有空试验一下
1，试试直接在“选取设备”框里直接输入夜神模拟器的地址 127.0.0.1:62001
（百度搜的，不确定地址是否正确）
2，程序闪退问题，需要一些debug的运行信息才能定位问题了，不过目前脚本并没有记录日志的功能（后续添加）

    另外后续的修改只是尝试添加些上层逻辑（比如访问线索、基建领取），adb连接模拟器的代码还是没变的，不会优化（水平有限
    exe打包的话，是打算修改积累到一定程度才做
    预计明天更新一下代码，gitee的打包也一起更新

**Comment by LoveYourEnemy** [comment]
> 刀客塔你好，
> 本人用的是雷电模拟器，没有尝试过在夜神模拟器使用脚本，有空试验一下
> 1，试试直接在“选取设备”框里直接输入夜神模拟器的地址 127.0.0.1:62001
> （百度搜的，不确定地址是否正确）
> 2，程序闪退问题，需要一些debug的运行信息才能定位问题了，不过目前脚本并没有记录日志的功能（后续添加）
> 
> ```
> 另外后续的修改只是尝试添加些上层逻辑（比如访问线索、基建领取），adb连接模拟器的代码还是没变的，不会优化（水平有限
> exe打包的话，是打算修改积累到一定程度才做
> 预计明天更新一下代码，gitee的打包也一起更新
> ```

感谢！您才是真正的刀客塔！
小生有空体验一下雷电。
至于adb地址问题，最初用同版本夜神模拟器的时候是出现了
Because the target computer actively refused, unable to connect. (10061) 的报错。
之后用的是这个网页的方法**https://www.programmersought.com/article/85352506724/**
误打误撞给解决了，但是会出现上面讲的1的情况。希望有帮助。

期待更新打包！

**Comment by zsppp** [comment]
exe打包已更新，闪退问题这边也用夜神模拟器复现了，需要一点时间看看


log信息
[adbError.log](https://github.com/zsppp/Arknights-Sora/files/6759261/adbError.log)

**Comment by LoveYourEnemy** [comment]
32位雷电模拟器4.0.57  2CPU 3072RAM 1280x720
v1.05下完美运行
1. 第一次打开exe便能检测到模拟器
2. 当前活动能够正常开始战斗
3. 主线完成战斗后能够正常领取每日以及好友线索交流
4. 结束音乐非常棒

（题外话:小生要正式弃暗投明使用雷电模拟器。
由于小生在有活动时还会FGO，特地在雷电上面看了一下FGO的运行情况。
相比在夜神模拟器无论32位或是64位都无法使FGO在超过30fps以上运行的情况下（_已设置高帧数_），雷电模拟器通过设置便简简单单地120fps）

对小生来说。目前夜神模拟器速度和稳定性都不佳（_夜神已卸载_）。如果您不是出于学习目的，小生认为没有必要花时间debug。
在此感谢刀客塔！

在这里也推荐各位看到这个的刀客塔遇到问题时，先尝试使用雷电模拟器。

**Comment by zsppp** [comment]
尝试了一下，确实难搞
但至少可以做个异常处理，来个报错什么的
