### ISSUE TITLE
之前遇到了adb server版本不对无法连接模拟器的问题

### ISSUE THREAD

**Issue by SrvenX-07** [zsppp/Arknights-Sora#3]
建议再readme.md里写上解决办法：
把\Arknights-Sora_v1.0.5\main\airtest\core\android\static\adb\windows的adb.exe替换为模拟器的adb.exe，即可正常连接
我的是夜神模拟器，其他模拟器也应该同理。

**Comment by zsppp** [comment]
感谢提供解决方法，近期会补充到readme.md

adb client 和 server 的版本不一致会出现这样的报错
`adb server version (36) doesn't match this client (40); killing...`

所以只要统一脚本和夜神模拟器的adb版本即可，
问了度娘试验一下，把脚本的 adb.exe 覆盖到夜神模拟器 bin/nox_adb.exe 也可以解决问题

**Comment by LoveYourEnemy** [comment]
> 感谢提供解决方法，近期会补充到readme.md
> 
> adb client 和 server 的版本不一致会出现这样的报错 `adb server version (36) doesn't match this client (40); killing...`
> 
> 所以只要统一脚本和夜神模拟器的adb版本即可， 问了度娘试验一下，把脚本的 adb.exe 覆盖到夜神模拟器 bin/nox_adb.exe 也可以解决问题

Hello~ 2.5周年更新,回来帮助测试看看还能不能用的时候发现这里已经更新到v1.0.7啦 
如果有时间的话麻烦gitee上面再打包一下~我既可以看看2.5周年改动有没有影响到脚本,也又可以开始肝起来了!

谢谢~

**Comment by zsppp** [comment]
> > 感谢提供解决方法，近期会补充到readme.md
> > adb client 和 server 的版本不一致会出现这样的报错 `adb server version (36) doesn't match this client (40); killing...`
> > 所以只要统一脚本和夜神模拟器的adb版本即可， 问了度娘试验一下，把脚本的 adb.exe 覆盖到夜神模拟器 bin/nox_adb.exe 也可以解决问题
> 
> Hello~ 2.5周年更新,回来帮助测试看看还能不能用的时候发现这里已经更新到v1.0.7啦 如果有时间的话麻烦gitee上面再打包一下~我既可以看看2.5周年改动有没有影响到脚本,也又可以开始肝起来了!
> 
> 谢谢~

Hi，
记得游戏更新过一次UI，脚本做了点调整才能用。
关于打包，我还不会做自动化构建，是手工操作运行构建命令再推上gitee，所以经常忘记（懒

建议有空搜索一下教程，尝试在windows下安装python环境，可以直接运行脚本文件
大概几个步骤
1. 安装`python3.8`
2. 更换pip软件源（从国内源下载扩展库速度比较快）
3. 使用`pip install`命令安装代码仓库下`requirements.txt`的依赖

刚刚我也把打包推到gitee了，祝顺利

**Comment by LoveYourEnemy** [comment]
感谢打包!
其实之前有试过装python,有可能各种依赖包没装好.结果是没有运行成功...
我按你的教程再试试Python步骤,感觉这次容易懂多啦!
